### ISSUE TITLE
Domain Diagram

### ISSUE THREAD

**Issue by quietHeliumRadiation** [ApolloSoen341/apollo-website#4]
From this week's meeting: 

Add star uml diagram to document
[https://docs.google.com/document/d/11Q7V23uK7rSmn__nUXm2qjJUtoA3f8tvI9nsXDD1aUU/edit](url)

**Comment by annarog** [comment]
@Ldhatter @rougal Take a look at the diagram and let me know if something we discussed is missing. Otherwise one of you can close the issue :)

https://drive.google.com/file/d/0B9EAqzqhw0IfdkhfMlE3VWZXVUk/view

**Comment by annarog** [comment]
Updated diagram after today's meeting discussion
https://drive.google.com/file/d/0B9EAqzqhw0Ifdl9OMXBOX0tqbXM/view
