### ISSUE TITLE
System Sequence Diagram-Save Preferences

### ISSUE THREAD

**Issue by sabr786** [ApolloSoen341/apollo-website#40]
Create a system sequence diagram for save preferences.   

@wahabwajahat @annarog @MatthewTeolis @jianhuang1314 @Ldhatter working on this.

**Comment by quietHeliumRadiation** [comment]
![saveprefs](https://cloud.githubusercontent.com/assets/13111600/13612769/46d2ce3c-e537-11e5-8b47-363746d397f4.jpg)

**Comment by quietHeliumRadiation** [comment]
@jianhuang1314  This should say navigate to "User Settings page"  and then User chooses to edit Preferences and then user changes prefs then user saves prefs

it should say
"User navigates to user settings page"
System displays user settings page
User chooses edit preferences section
System displays preferences
User changes preferences
System displays changes in preferences
User saves preference
System displays saved preferences
