### ISSUE TITLE
Sequence Diagrams - Save Preferences

### ISSUE THREAD

**Issue by quietHeliumRadiation** [ApolloSoen341/apollo-website#42]
Sequence diagram for save preferences.

Done all together by:
@paboukasm , @annarog , @sabr786 , @jianhuang1314 , @MatthewTeolis , and Liuai

**Comment by Ldhatter** [comment]
![saveprefs](https://cloud.githubusercontent.com/assets/13111600/13612982/18383110-e538-11e5-88d4-4e4ea90c7a65.jpg)

**Comment by Ldhatter** [comment]
@jianhuang1314  it should say "User navigates to user settings page"
System displays user settings page
User chooses edit preferences section
System displays preferences
User changes preferences
System displays changes in preferences
User saves preference
System displays saved preferences

**Comment by quietHeliumRadiation** [comment]
![savepreferences](https://cloud.githubusercontent.com/assets/13111600/13644476/fbca803e-e5f3-11e5-8a67-e5c121a65a1d.JPG)

**Comment by paboukasm** [comment]
Completed system diagram for Save Preferences.
