### ISSUE TITLE
Design: Scheduler (select a course)

### ISSUE THREAD

**Issue by quietHeliumRadiation** [ApolloSoen341/apollo-website#48]
Scheduler page. First step to select/filter courses.
See slack design thread.

(completed by Liuai and Francis)

![slack for ios upload 3](https://cloud.githubusercontent.com/assets/13111600/13338856/352633d4-dbf2-11e5-8d62-58e1a0b4862e.jpg)

**Comment by Ldhatter** [comment]
![scheduler-selectcourse](https://cloud.githubusercontent.com/assets/13111600/13339062/dc24fca0-dbf3-11e5-8958-38b5e15b0e4d.jpg)

**Comment by quietHeliumRadiation** [comment]
![apollo_scheduler-selectcourse](https://cloud.githubusercontent.com/assets/13111600/13586200/928cd886-e48d-11e5-8b34-b75aacc294d8.jpg)

**Comment by quietHeliumRadiation** [comment]
We need to add a spot to include which semester this is for.
