### ISSUE TITLE
Design: Scheduler (Generated schedules)

### ISSUE THREAD

**Issue by quietHeliumRadiation** [ApolloSoen341/apollo-website#49]
Scheduler page after user has selected courses and requests to generate schedules.
See slack design thread.

![slack for ios upload 4](https://cloud.githubusercontent.com/assets/13111600/13338889/8af40566-dbf2-11e5-9eb6-a3091f7ff016.jpg)

**Comment by quietHeliumRadiation** [comment]
We need to add a way to go back to selecting the courses / edit the ones that are there.
Or we could leave the search input box and the generate button. If the user begins to type in the search field then new courses could drop down? Prefs/ generated courses could disappear?

**Comment by Ldhatter** [comment]
![apollo_scheduler-generatedschedules-wip](https://cloud.githubusercontent.com/assets/13111600/13505847/1459f6ca-e149-11e5-82e1-c81d2ceeb9ed.JPG)

**Comment by quietHeliumRadiation** [comment]
Had to make font smaller. 
To remember for other pages:
Headers: 30 px
Text inside search/buttons/prefs: 25px

**Comment by Ldhatter** [comment]
![apollo_scheduler-generatedschedules](https://cloud.githubusercontent.com/assets/13111600/13562384/2c675e32-e406-11e5-974f-23386f87923c.jpg)

**Comment by Ldhatter** [comment]
![apollo_scheduler-generatedschedules](https://cloud.githubusercontent.com/assets/13111600/13586657/47f2d642-e490-11e5-820e-12953ab3e370.jpg)

**Comment by quietHeliumRadiation** [comment]
Added a "Return to Courses" button

**Comment by quietHeliumRadiation** [comment]
![apollo_scheduler-generatedschedules](https://cloud.githubusercontent.com/assets/13111600/13613400/f3967798-e539-11e5-8336-90edc19972c6.jpg)
